// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="line_buffer_19,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.573000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=1,HLS_SYN_FF=337,HLS_SYN_LUT=1068}" *)

module line_buffer_19 (
        ap_clk,
        ap_rst,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_pp0_stage0 = 9'd16;
parameter    ap_ST_fsm_state7 = 9'd32;
parameter    ap_ST_fsm_state8 = 9'd64;
parameter    ap_ST_fsm_pp1_stage0 = 9'd128;
parameter    ap_ST_fsm_state11 = 9'd256;

input   ap_clk;
input   ap_rst;
input  [15:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [15:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;

reg input_V_V_read;
reg output_V_V_write;

reg    input_V_V_blk_n;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg   [0:0] out_of_bounds_reg_921;
reg    output_V_V_blk_n;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [4:0] pin_reg_344;
reg   [9:0] phi_mul1_reg_355;
reg   [0:0] exitcond_flatten3_reg_427;
reg   [0:0] exitcond4_reg_438;
reg   [5:0] pkern_reg_449;
reg   [1:0] wkern_reg_460;
reg   [7:0] indvar_flatten1_reg_471;
reg   [1:0] hkern_reg_482;
reg   [8:0] indvar_flatten2_reg_493;
wire   [4:0] tmp_1_fu_504_p2;
wire    ap_CS_fsm_state2;
wire   [9:0] next_mul_fu_510_p2;
wire   [15:0] win_133_cast_fu_522_p1;
wire    ap_CS_fsm_state3;
wire   [4:0] hout_mid2_fu_532_p3;
reg   [4:0] hout_mid2_reg_890;
wire   [15:0] tmp_4_cast_fu_546_p1;
reg   [15:0] tmp_4_cast_reg_895;
wire   [8:0] indvar_flatten_next1_fu_550_p2;
reg   [8:0] indvar_flatten_next1_reg_901;
wire   [14:0] tmp_2_fu_556_p1;
wire    ap_CS_fsm_state4;
wire   [4:0] wout_mid_fu_560_p3;
reg   [4:0] wout_mid_reg_911;
wire   [0:0] or_cond_fu_595_p2;
reg   [0:0] or_cond_reg_917;
wire   [0:0] out_of_bounds_fu_637_p2;
wire   [4:0] pin_1_fu_647_p2;
reg   [4:0] pin_1_reg_925;
reg    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] next_mul1_fu_653_p2;
reg   [9:0] next_mul1_reg_935;
wire   [63:0] tmp_23_cast_fu_669_p1;
reg   [63:0] tmp_23_cast_reg_940;
reg   [9:0] buffer_val_1_V_addr_reg_945;
reg   [9:0] buffer_val_2_V_addr_reg_951;
wire   [0:0] exitcond3_fu_675_p2;
reg   [0:0] exitcond3_reg_957;
wire   [0:0] tmp_12_fu_681_p2;
wire    ap_CS_fsm_state7;
wire   [15:0] hin_fu_687_p2;
wire   [0:0] tmp_15_fu_694_p2;
wire   [15:0] win_fu_699_p2;
wire   [1:0] hkern_mid2_fu_731_p3;
reg   [1:0] hkern_mid2_reg_979;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_state9_pp1_stage0_iter0;
reg    ap_block_state10_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [1:0] wkern_mid2_fu_759_p3;
reg   [1:0] wkern_mid2_reg_985;
wire   [5:0] pkern_1_fu_790_p2;
reg   [5:0] pkern_1_reg_1005;
wire   [7:0] indvar_flatten_next_fu_802_p3;
reg   [7:0] indvar_flatten_next_reg_1010;
wire   [8:0] indvar_flatten_next2_fu_810_p2;
reg   [8:0] indvar_flatten_next2_reg_1015;
wire   [0:0] exitcond_fu_816_p2;
reg   [0:0] exitcond_reg_1020;
wire   [0:0] exitcond_flatten_fu_822_p2;
reg   [0:0] exitcond_flatten_reg_1025;
wire   [0:0] exitcond_flatten2_fu_828_p2;
reg   [0:0] exitcond_flatten2_reg_1030;
wire   [4:0] wout_1_fu_846_p2;
wire    ap_CS_fsm_state11;
wire   [0:0] exitcond2_fu_851_p2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp1_stage0_subdone;
reg   [9:0] buffer_val_0_V_address0;
reg    buffer_val_0_V_ce0;
reg    buffer_val_0_V_we0;
wire   [15:0] buffer_val_0_V_q0;
reg   [9:0] buffer_val_1_V_address0;
reg    buffer_val_1_V_ce0;
wire   [15:0] buffer_val_1_V_q0;
reg    buffer_val_1_V_ce1;
reg    buffer_val_1_V_we1;
reg   [9:0] buffer_val_2_V_address0;
reg    buffer_val_2_V_ce0;
wire   [15:0] buffer_val_2_V_q0;
reg    buffer_val_2_V_ce1;
reg    buffer_val_2_V_we1;
reg   [4:0] tmp_reg_231;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_3_fu_516_p2;
reg   [9:0] phi_mul_reg_242;
reg   [0:0] exitcond1_reg_253;
wire   [0:0] exitcond_flatten1_fu_857_p2;
reg   [14:0] win_4_reg_390;
reg   [14:0] win_s_reg_265;
reg   [15:0] hin_4_reg_378;
reg   [15:0] hin_s_reg_276;
reg   [4:0] wout_reg_288;
reg   [4:0] hout_reg_300;
reg   [8:0] indvar_flatten_reg_311;
reg   [15:0] hin_2_reg_323;
wire    ap_CS_fsm_state8;
reg   [15:0] win_2_reg_334;
reg   [4:0] ap_phi_mux_pin_phi_fu_348_p4;
reg   [9:0] ap_phi_mux_phi_mul1_phi_fu_359_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_13_reg_366;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_13_reg_366;
reg   [15:0] hin_3_reg_402;
reg   [15:0] win_3_reg_414;
reg   [0:0] ap_phi_mux_exitcond_flatten3_phi_fu_431_p4;
reg   [0:0] ap_phi_mux_exitcond4_phi_fu_442_p4;
reg   [5:0] ap_phi_mux_pkern_phi_fu_453_p4;
reg   [1:0] ap_phi_mux_wkern_phi_fu_464_p4;
reg   [7:0] ap_phi_mux_indvar_flatten1_phi_fu_475_p4;
reg   [1:0] ap_phi_mux_hkern_phi_fu_486_p4;
reg   [8:0] ap_phi_mux_indvar_flatten2_phi_fu_497_p4;
wire  signed [63:0] tmp_26_cast_fu_784_p1;
wire   [15:0] out_val_V_fu_834_p5;
reg    ap_block_pp1_stage0_01001;
wire   [4:0] hout_1_fu_526_p2;
wire   [4:0] tmp_4_fu_540_p2;
wire   [4:0] tmp_7_fu_568_p2;
wire   [15:0] tmp_7_cast_fu_574_p1;
wire   [0:0] slt_fu_578_p2;
wire   [0:0] rev_fu_584_p2;
wire   [0:0] tmp_5_fu_590_p2;
wire   [0:0] tmp_6_fu_601_p2;
wire   [0:0] tmp_9_fu_607_p2;
wire   [0:0] tmp_8_fu_613_p2;
wire   [0:0] tmp_10_fu_619_p2;
wire   [0:0] tmp2_fu_631_p2;
wire   [0:0] tmp1_fu_625_p2;
wire   [10:0] phi_mul35_cast_fu_643_p1;
wire   [10:0] tmp_14_fu_659_p1;
wire   [10:0] tmp_16_fu_663_p2;
wire   [0:0] not_exitcond_flatten_fu_719_p2;
wire   [1:0] hkern_1_fu_705_p2;
wire   [1:0] wkern_mid_fu_711_p3;
wire   [0:0] exitcond_mid_fu_725_p2;
wire   [0:0] tmp_17_fu_745_p2;
wire   [1:0] wkern_1_fu_739_p2;
wire   [5:0] pkern_mid2_fu_751_p3;
wire   [4:0] tmp_27_cast_fu_771_p1;
wire   [4:0] col_assign_fu_775_p2;
wire   [10:0] grp_fu_863_p3;
wire   [7:0] indvar_flatten_op_fu_796_p2;
wire   [5:0] grp_fu_863_p0;
wire   [5:0] grp_fu_863_p1;
wire   [4:0] grp_fu_863_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [10:0] grp_fu_863_p00;
wire   [10:0] grp_fu_863_p20;
reg    ap_condition_124;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

line_buffer_19_bubkb #(
    .DataWidth( 16 ),
    .AddressRange( 736 ),
    .AddressWidth( 10 ))
buffer_val_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buffer_val_0_V_address0),
    .ce0(buffer_val_0_V_ce0),
    .we0(buffer_val_0_V_we0),
    .d0(buffer_val_1_V_q0),
    .q0(buffer_val_0_V_q0)
);

line_buffer_19_bucud #(
    .DataWidth( 16 ),
    .AddressRange( 736 ),
    .AddressWidth( 10 ))
buffer_val_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buffer_val_1_V_address0),
    .ce0(buffer_val_1_V_ce0),
    .q0(buffer_val_1_V_q0),
    .address1(buffer_val_1_V_addr_reg_945),
    .ce1(buffer_val_1_V_ce1),
    .we1(buffer_val_1_V_we1),
    .d1(buffer_val_2_V_q0)
);

line_buffer_19_bucud #(
    .DataWidth( 16 ),
    .AddressRange( 736 ),
    .AddressWidth( 10 ))
buffer_val_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buffer_val_2_V_address0),
    .ce0(buffer_val_2_V_ce0),
    .q0(buffer_val_2_V_q0),
    .address1(buffer_val_2_V_addr_reg_951),
    .ce1(buffer_val_2_V_ce1),
    .we1(buffer_val_2_V_we1),
    .d1(ap_phi_reg_pp0_iter1_tmp_13_reg_366)
);

line_buffer_19_mueOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
line_buffer_19_mueOg_U1(
    .din0(buffer_val_0_V_q0),
    .din1(buffer_val_1_V_q0),
    .din2(buffer_val_2_V_q0),
    .din3(hkern_mid2_reg_979),
    .dout(out_val_V_fu_834_p5)
);

line_buffer_19_mafYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 11 ))
line_buffer_19_mafYi_U2(
    .din0(grp_fu_863_p0),
    .din1(grp_fu_863_p1),
    .din2(grp_fu_863_p2),
    .dout(grp_fu_863_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond3_fu_675_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_595_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_595_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten2_fu_828_p2 == 1'd1))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_124)) begin
        if ((out_of_bounds_reg_921 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_tmp_13_reg_366 <= 16'd0;
        end else if ((out_of_bounds_reg_921 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_tmp_13_reg_366 <= input_V_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_13_reg_366 <= ap_phi_reg_pp0_iter0_tmp_13_reg_366;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_516_p2 == 1'd1))) begin
        exitcond1_reg_253 <= 1'd0;
    end else if (((exitcond_flatten1_fu_857_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        exitcond1_reg_253 <= exitcond2_fu_851_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond4_reg_438 <= exitcond_reg_1020;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
        exitcond4_reg_438 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond_flatten3_reg_427 <= exitcond_flatten_reg_1025;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
        exitcond_flatten3_reg_427 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        hin_2_reg_323 <= hin_s_reg_276;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hin_2_reg_323 <= hin_3_reg_402;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (or_cond_reg_917 == 1'd1))) begin
        if (((tmp_15_fu_694_p2 == 1'd0) & (tmp_12_fu_681_p2 == 1'd0))) begin
            hin_3_reg_402 <= hin_fu_687_p2;
        end else if ((tmp_12_fu_681_p2 == 1'd1)) begin
            hin_3_reg_402 <= hin_2_reg_323;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        hin_4_reg_378 <= hin_2_reg_323;
    end else if (((tmp_12_fu_681_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (tmp_15_fu_694_p2 == 1'd1) & (or_cond_reg_917 == 1'd1))) begin
        hin_4_reg_378 <= hin_fu_687_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_516_p2 == 1'd1))) begin
        hin_s_reg_276 <= 16'd0;
    end else if (((exitcond_flatten1_fu_857_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        hin_s_reg_276 <= hin_4_reg_378;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        hkern_reg_482 <= hkern_mid2_reg_979;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
        hkern_reg_482 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_516_p2 == 1'd1))) begin
        hout_reg_300 <= 5'd0;
    end else if (((exitcond_flatten1_fu_857_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        hout_reg_300 <= hout_mid2_reg_890;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        indvar_flatten1_reg_471 <= indvar_flatten_next_reg_1010;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
        indvar_flatten1_reg_471 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        indvar_flatten2_reg_493 <= indvar_flatten_next2_reg_1015;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
        indvar_flatten2_reg_493 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_516_p2 == 1'd1))) begin
        indvar_flatten_reg_311 <= 9'd0;
    end else if (((exitcond_flatten1_fu_857_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        indvar_flatten_reg_311 <= indvar_flatten_next1_reg_901;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_reg_957 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        phi_mul1_reg_355 <= next_mul1_reg_935;
    end else if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_595_p2 == 1'd1))) begin
        phi_mul1_reg_355 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_516_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_mul_reg_242 <= next_mul_fu_510_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        phi_mul_reg_242 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_reg_957 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pin_reg_344 <= pin_1_reg_925;
    end else if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_595_p2 == 1'd1))) begin
        pin_reg_344 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        pkern_reg_449 <= pkern_1_reg_1005;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
        pkern_reg_449 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_516_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_reg_231 <= tmp_1_fu_504_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_reg_231 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        win_2_reg_334 <= win_133_cast_fu_522_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        win_2_reg_334 <= win_3_reg_414;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (or_cond_reg_917 == 1'd1))) begin
        if (((tmp_15_fu_694_p2 == 1'd0) & (tmp_12_fu_681_p2 == 1'd0))) begin
            win_3_reg_414 <= 16'd0;
        end else if ((tmp_12_fu_681_p2 == 1'd1)) begin
            win_3_reg_414 <= win_fu_699_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        win_4_reg_390 <= tmp_2_fu_556_p1;
    end else if (((tmp_12_fu_681_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (tmp_15_fu_694_p2 == 1'd1) & (or_cond_reg_917 == 1'd1))) begin
        win_4_reg_390 <= 15'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_516_p2 == 1'd1))) begin
        win_s_reg_265 <= 15'd0;
    end else if (((exitcond_flatten1_fu_857_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        win_s_reg_265 <= win_4_reg_390;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        wkern_reg_460 <= wkern_mid2_reg_985;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
        wkern_reg_460 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_516_p2 == 1'd1))) begin
        wout_reg_288 <= 5'd0;
    end else if (((exitcond_flatten1_fu_857_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        wout_reg_288 <= wout_1_fu_846_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_1_V_addr_reg_945 <= tmp_23_cast_fu_669_p1;
        buffer_val_2_V_addr_reg_951 <= tmp_23_cast_fu_669_p1;
        exitcond3_reg_957 <= exitcond3_fu_675_p2;
        tmp_23_cast_reg_940[10 : 0] <= tmp_23_cast_fu_669_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond_flatten2_reg_1030 <= exitcond_flatten2_fu_828_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond_flatten_reg_1025 <= exitcond_flatten_fu_822_p2;
        exitcond_reg_1020 <= exitcond_fu_816_p2;
        hkern_mid2_reg_979 <= hkern_mid2_fu_731_p3;
        indvar_flatten_next2_reg_1015 <= indvar_flatten_next2_fu_810_p2;
        indvar_flatten_next_reg_1010 <= indvar_flatten_next_fu_802_p3;
        pkern_1_reg_1005 <= pkern_1_fu_790_p2;
        wkern_mid2_reg_985 <= wkern_mid2_fu_759_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        hout_mid2_reg_890 <= hout_mid2_fu_532_p3;
        indvar_flatten_next1_reg_901 <= indvar_flatten_next1_fu_550_p2;
        tmp_4_cast_reg_895[4 : 0] <= tmp_4_cast_fu_546_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        next_mul1_reg_935 <= next_mul1_fu_653_p2;
        pin_1_reg_925 <= pin_1_fu_647_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        or_cond_reg_917 <= or_cond_fu_595_p2;
        wout_mid_reg_911 <= wout_mid_fu_560_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_595_p2 == 1'd1))) begin
        out_of_bounds_reg_921 <= out_of_bounds_fu_637_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_exitcond4_phi_fu_442_p4 = exitcond_reg_1020;
    end else begin
        ap_phi_mux_exitcond4_phi_fu_442_p4 = exitcond4_reg_438;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_exitcond_flatten3_phi_fu_431_p4 = exitcond_flatten_reg_1025;
    end else begin
        ap_phi_mux_exitcond_flatten3_phi_fu_431_p4 = exitcond_flatten3_reg_427;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_hkern_phi_fu_486_p4 = hkern_mid2_reg_979;
    end else begin
        ap_phi_mux_hkern_phi_fu_486_p4 = hkern_reg_482;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_indvar_flatten1_phi_fu_475_p4 = indvar_flatten_next_reg_1010;
    end else begin
        ap_phi_mux_indvar_flatten1_phi_fu_475_p4 = indvar_flatten1_reg_471;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_indvar_flatten2_phi_fu_497_p4 = indvar_flatten_next2_reg_1015;
    end else begin
        ap_phi_mux_indvar_flatten2_phi_fu_497_p4 = indvar_flatten2_reg_493;
    end
end

always @ (*) begin
    if (((exitcond3_reg_957 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_phi_mul1_phi_fu_359_p4 = next_mul1_reg_935;
    end else begin
        ap_phi_mux_phi_mul1_phi_fu_359_p4 = phi_mul1_reg_355;
    end
end

always @ (*) begin
    if (((exitcond3_reg_957 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_pin_phi_fu_348_p4 = pin_1_reg_925;
    end else begin
        ap_phi_mux_pin_phi_fu_348_p4 = pin_reg_344;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_pkern_phi_fu_453_p4 = pkern_1_reg_1005;
    end else begin
        ap_phi_mux_pkern_phi_fu_453_p4 = pkern_reg_449;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1030 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_wkern_phi_fu_464_p4 = wkern_mid2_reg_985;
    end else begin
        ap_phi_mux_wkern_phi_fu_464_p4 = wkern_reg_460;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        buffer_val_0_V_address0 = tmp_26_cast_fu_784_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        buffer_val_0_V_address0 = tmp_23_cast_reg_940;
    end else begin
        buffer_val_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buffer_val_0_V_ce0 = 1'b1;
    end else begin
        buffer_val_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_0_V_we0 = 1'b1;
    end else begin
        buffer_val_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        buffer_val_1_V_address0 = tmp_26_cast_fu_784_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_val_1_V_address0 = tmp_23_cast_fu_669_p1;
    end else begin
        buffer_val_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buffer_val_1_V_ce0 = 1'b1;
    end else begin
        buffer_val_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_1_V_ce1 = 1'b1;
    end else begin
        buffer_val_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_1_V_we1 = 1'b1;
    end else begin
        buffer_val_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        buffer_val_2_V_address0 = tmp_26_cast_fu_784_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_val_2_V_address0 = tmp_23_cast_fu_669_p1;
    end else begin
        buffer_val_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buffer_val_2_V_ce0 = 1'b1;
    end else begin
        buffer_val_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_2_V_ce1 = 1'b1;
    end else begin
        buffer_val_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_2_V_we1 = 1'b1;
    end else begin
        buffer_val_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((out_of_bounds_reg_921 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_V_blk_n = input_V_V_empty_n;
    end else begin
        input_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_of_bounds_reg_921 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_V_V_read = 1'b1;
    end else begin
        input_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        output_V_V_blk_n = output_V_V_full_n;
    end else begin
        output_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_V_V_write = 1'b1;
    end else begin
        output_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_516_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_595_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_917 == 1'd0) | ((tmp_12_fu_681_p2 == 1'd0) & (tmp_15_fu_694_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (exitcond_flatten1_fu_857_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_of_bounds_reg_921 == 1'd0) & (input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_of_bounds_reg_921 == 1'd0) & (input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp1_stage0_iter1 = (output_V_V_full_n == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter0 = ((out_of_bounds_reg_921 == 1'd0) & (input_V_V_empty_n == 1'b0));
end

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_124 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_tmp_13_reg_366 = 'bx;

assign col_assign_fu_775_p2 = (tmp_27_cast_fu_771_p1 + wout_mid_reg_911);

assign exitcond2_fu_851_p2 = ((wout_1_fu_846_p2 == 5'd21) ? 1'b1 : 1'b0);

assign exitcond3_fu_675_p2 = ((ap_phi_mux_pin_phi_fu_348_p4 == 5'd31) ? 1'b1 : 1'b0);

assign exitcond_flatten1_fu_857_p2 = ((indvar_flatten_reg_311 == 9'd440) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_828_p2 = ((ap_phi_mux_indvar_flatten2_phi_fu_497_p4 == 9'd287) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_822_p2 = ((indvar_flatten_next_fu_802_p3 == 8'd96) ? 1'b1 : 1'b0);

assign exitcond_fu_816_p2 = ((pkern_1_fu_790_p2 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond_mid_fu_725_p2 = (not_exitcond_flatten_fu_719_p2 & ap_phi_mux_exitcond4_phi_fu_442_p4);

assign grp_fu_863_p0 = grp_fu_863_p00;

assign grp_fu_863_p00 = pkern_mid2_fu_751_p3;

assign grp_fu_863_p1 = 11'd23;

assign grp_fu_863_p2 = grp_fu_863_p20;

assign grp_fu_863_p20 = col_assign_fu_775_p2;

assign hin_fu_687_p2 = (hin_2_reg_323 + 16'd1);

assign hkern_1_fu_705_p2 = (ap_phi_mux_hkern_phi_fu_486_p4 + 2'd1);

assign hkern_mid2_fu_731_p3 = ((ap_phi_mux_exitcond_flatten3_phi_fu_431_p4[0:0] === 1'b1) ? hkern_1_fu_705_p2 : ap_phi_mux_hkern_phi_fu_486_p4);

assign hout_1_fu_526_p2 = (hout_reg_300 + 5'd1);

assign hout_mid2_fu_532_p3 = ((exitcond1_reg_253[0:0] === 1'b1) ? hout_1_fu_526_p2 : hout_reg_300);

assign indvar_flatten_next1_fu_550_p2 = (indvar_flatten_reg_311 + 9'd1);

assign indvar_flatten_next2_fu_810_p2 = (ap_phi_mux_indvar_flatten2_phi_fu_497_p4 + 9'd1);

assign indvar_flatten_next_fu_802_p3 = ((ap_phi_mux_exitcond_flatten3_phi_fu_431_p4[0:0] === 1'b1) ? 8'd1 : indvar_flatten_op_fu_796_p2);

assign indvar_flatten_op_fu_796_p2 = (ap_phi_mux_indvar_flatten1_phi_fu_475_p4 + 8'd1);

assign next_mul1_fu_653_p2 = (10'd23 + ap_phi_mux_phi_mul1_phi_fu_359_p4);

assign next_mul_fu_510_p2 = (phi_mul_reg_242 + 10'd23);

assign not_exitcond_flatten_fu_719_p2 = (ap_phi_mux_exitcond_flatten3_phi_fu_431_p4 ^ 1'd1);

assign or_cond_fu_595_p2 = (tmp_5_fu_590_p2 | rev_fu_584_p2);

assign out_of_bounds_fu_637_p2 = (tmp2_fu_631_p2 | tmp1_fu_625_p2);

assign output_V_V_din = out_val_V_fu_834_p5;

assign phi_mul35_cast_fu_643_p1 = ap_phi_mux_phi_mul1_phi_fu_359_p4;

assign pin_1_fu_647_p2 = (ap_phi_mux_pin_phi_fu_348_p4 + 5'd1);

assign pkern_1_fu_790_p2 = (pkern_mid2_fu_751_p3 + 6'd1);

assign pkern_mid2_fu_751_p3 = ((tmp_17_fu_745_p2[0:0] === 1'b1) ? 6'd0 : ap_phi_mux_pkern_phi_fu_453_p4);

assign rev_fu_584_p2 = (slt_fu_578_p2 ^ 1'd1);

assign slt_fu_578_p2 = (($signed(tmp_7_cast_fu_574_p1) < $signed(win_2_reg_334)) ? 1'b1 : 1'b0);

assign tmp1_fu_625_p2 = (tmp_9_fu_607_p2 | tmp_6_fu_601_p2);

assign tmp2_fu_631_p2 = (tmp_8_fu_613_p2 | tmp_10_fu_619_p2);

assign tmp_10_fu_619_p2 = (($signed(win_2_reg_334) > $signed(16'd21)) ? 1'b1 : 1'b0);

assign tmp_12_fu_681_p2 = (($signed(win_2_reg_334) < $signed(16'd22)) ? 1'b1 : 1'b0);

assign tmp_14_fu_659_p1 = win_2_reg_334[10:0];

assign tmp_15_fu_694_p2 = (($signed(hin_fu_687_p2) > $signed(tmp_4_cast_reg_895)) ? 1'b1 : 1'b0);

assign tmp_16_fu_663_p2 = (phi_mul35_cast_fu_643_p1 + tmp_14_fu_659_p1);

assign tmp_17_fu_745_p2 = (exitcond_mid_fu_725_p2 | ap_phi_mux_exitcond_flatten3_phi_fu_431_p4);

assign tmp_1_fu_504_p2 = (tmp_reg_231 + 5'd1);

assign tmp_23_cast_fu_669_p1 = tmp_16_fu_663_p2;

assign tmp_26_cast_fu_784_p1 = $signed(grp_fu_863_p3);

assign tmp_27_cast_fu_771_p1 = wkern_mid2_fu_759_p3;

assign tmp_2_fu_556_p1 = win_2_reg_334[14:0];

assign tmp_3_fu_516_p2 = ((tmp_reg_231 == 5'd31) ? 1'b1 : 1'b0);

assign tmp_4_cast_fu_546_p1 = tmp_4_fu_540_p2;

assign tmp_4_fu_540_p2 = (hout_mid2_fu_532_p3 + 5'd2);

assign tmp_5_fu_590_p2 = (($signed(hin_2_reg_323) < $signed(tmp_4_cast_reg_895)) ? 1'b1 : 1'b0);

assign tmp_6_fu_601_p2 = (($signed(hin_2_reg_323) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign tmp_7_cast_fu_574_p1 = tmp_7_fu_568_p2;

assign tmp_7_fu_568_p2 = (5'd2 + wout_mid_fu_560_p3);

assign tmp_8_fu_613_p2 = (($signed(win_2_reg_334) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign tmp_9_fu_607_p2 = (($signed(hin_2_reg_323) > $signed(16'd21)) ? 1'b1 : 1'b0);

assign win_133_cast_fu_522_p1 = win_s_reg_265;

assign win_fu_699_p2 = (win_2_reg_334 + 16'd1);

assign wkern_1_fu_739_p2 = (wkern_mid_fu_711_p3 + 2'd1);

assign wkern_mid2_fu_759_p3 = ((exitcond_mid_fu_725_p2[0:0] === 1'b1) ? wkern_1_fu_739_p2 : wkern_mid_fu_711_p3);

assign wkern_mid_fu_711_p3 = ((ap_phi_mux_exitcond_flatten3_phi_fu_431_p4[0:0] === 1'b1) ? 2'd0 : ap_phi_mux_wkern_phi_fu_464_p4);

assign wout_1_fu_846_p2 = (wout_mid_reg_911 + 5'd1);

assign wout_mid_fu_560_p3 = ((exitcond1_reg_253[0:0] === 1'b1) ? 5'd0 : wout_reg_288);

always @ (posedge ap_clk) begin
    tmp_4_cast_reg_895[15:5] <= 11'b00000000000;
    tmp_23_cast_reg_940[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //line_buffer_19
