// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="line_buffer_13,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.661000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=344,HLS_SYN_LUT=1038}" *)

module line_buffer_13 (
        ap_clk,
        ap_rst_n,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_pp0_stage0 = 9'd16;
parameter    ap_ST_fsm_state7 = 9'd32;
parameter    ap_ST_fsm_state8 = 9'd64;
parameter    ap_ST_fsm_pp1_stage0 = 9'd128;
parameter    ap_ST_fsm_state12 = 9'd256;

input   ap_clk;
input   ap_rst_n;
input  [15:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [15:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;

reg input_V_V_read;
reg output_V_V_write;

reg    ap_rst_n_inv;
reg    input_V_V_blk_n;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg   [0:0] out_of_bounds_reg_940;
reg    output_V_V_blk_n;
reg    ap_enable_reg_pp1_iter2;
wire    ap_block_pp1_stage0;
reg   [4:0] pin_reg_343;
reg   [0:0] exitcond_flatten3_reg_415;
reg   [0:0] exitcond4_reg_427;
reg   [5:0] pkern_reg_438;
reg   [1:0] wkern_reg_449;
reg   [7:0] indvar_flatten1_reg_460;
reg   [8:0] indvar_flatten2_reg_471;
reg   [1:0] hkern_reg_482;
wire   [4:0] tmp_1_fu_493_p2;
wire    ap_CS_fsm_state2;
wire   [15:0] win_138_cast_fu_505_p1;
wire    ap_CS_fsm_state3;
wire   [6:0] hout_mid2_fu_515_p3;
reg   [6:0] hout_mid2_reg_909;
wire   [15:0] tmp_4_cast_fu_529_p1;
reg   [15:0] tmp_4_cast_reg_914;
wire   [11:0] indvar_flatten_next1_fu_533_p2;
reg   [11:0] indvar_flatten_next1_reg_920;
wire   [14:0] tmp_2_fu_539_p1;
wire    ap_CS_fsm_state4;
wire   [6:0] wout_mid_fu_543_p3;
reg   [6:0] wout_mid_reg_930;
wire   [0:0] or_cond_fu_578_p2;
reg   [0:0] or_cond_reg_936;
wire   [0:0] out_of_bounds_fu_620_p2;
wire   [4:0] pin_1_fu_626_p2;
reg   [4:0] pin_1_reg_944;
reg    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] tmp_24_cast_fu_672_p1;
reg   [63:0] tmp_24_cast_reg_954;
reg   [11:0] buffer_val_1_V_addr_reg_959;
reg   [11:0] buffer_val_2_V_addr_reg_965;
wire   [0:0] exitcond3_fu_678_p2;
reg   [0:0] exitcond3_reg_971;
wire   [0:0] tmp_12_fu_684_p2;
wire    ap_CS_fsm_state7;
wire   [15:0] hin_fu_690_p2;
wire   [0:0] tmp_15_fu_697_p2;
wire   [15:0] win_fu_702_p2;
wire   [5:0] pkern_mid2_fu_740_p3;
reg   [5:0] pkern_mid2_reg_993;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state9_pp1_stage0_iter0;
wire    ap_block_state10_pp1_stage0_iter1;
reg    ap_block_state11_pp1_stage0_iter2;
reg    ap_block_pp1_stage0_11001;
wire   [1:0] wkern_mid2_fu_748_p3;
reg   [1:0] wkern_mid2_reg_999;
reg    ap_enable_reg_pp1_iter0;
wire   [6:0] col_assign_fu_760_p2;
reg   [6:0] col_assign_reg_1004;
wire   [5:0] pkern_1_fu_765_p2;
reg   [5:0] pkern_1_reg_1009;
wire   [7:0] indvar_flatten_next_fu_777_p3;
reg   [7:0] indvar_flatten_next_reg_1014;
wire   [8:0] indvar_flatten_next2_fu_785_p2;
reg   [8:0] indvar_flatten_next2_reg_1019;
wire   [0:0] exitcond_fu_791_p2;
reg   [0:0] exitcond_reg_1024;
wire   [0:0] exitcond_flatten_fu_797_p2;
reg   [0:0] exitcond_flatten_reg_1029;
wire   [0:0] exitcond_flatten2_fu_803_p2;
reg   [0:0] exitcond_flatten2_reg_1034;
reg   [0:0] ap_reg_pp1_iter1_exitcond_flatten2_reg_1034;
wire   [1:0] hkern_mid2_fu_815_p3;
reg   [1:0] hkern_mid2_reg_1038;
reg    ap_enable_reg_pp1_iter1;
wire   [6:0] wout_1_fu_879_p2;
wire    ap_CS_fsm_state12;
wire   [0:0] exitcond2_fu_884_p2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp1_stage0_subdone;
reg   [11:0] buffer_val_0_V_address0;
reg    buffer_val_0_V_ce0;
reg    buffer_val_0_V_we0;
wire   [15:0] buffer_val_0_V_q0;
reg   [11:0] buffer_val_1_V_address0;
reg    buffer_val_1_V_ce0;
wire   [15:0] buffer_val_1_V_q0;
reg    buffer_val_1_V_ce1;
reg    buffer_val_1_V_we1;
reg   [11:0] buffer_val_2_V_address0;
reg    buffer_val_2_V_ce0;
wire   [15:0] buffer_val_2_V_q0;
reg    buffer_val_2_V_ce1;
reg    buffer_val_2_V_we1;
reg   [4:0] tmp_reg_241;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_3_fu_499_p2;
reg   [0:0] exitcond1_reg_252;
wire   [0:0] exitcond_flatten1_fu_890_p2;
reg   [14:0] win_4_reg_378;
reg   [14:0] win_s_reg_264;
reg   [15:0] hin_4_reg_366;
reg   [15:0] hin_s_reg_275;
reg   [6:0] wout_reg_287;
reg   [6:0] hout_reg_299;
reg   [11:0] indvar_flatten_reg_310;
reg   [15:0] hin_2_reg_322;
wire    ap_CS_fsm_state8;
reg   [15:0] win_2_reg_333;
reg   [4:0] ap_phi_mux_pin_phi_fu_347_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_tmp_13_reg_354;
reg   [15:0] ap_phi_reg_pp0_iter1_tmp_13_reg_354;
reg   [15:0] hin_3_reg_390;
reg   [15:0] win_3_reg_402;
reg   [0:0] ap_phi_mux_exitcond_flatten3_phi_fu_419_p4;
reg   [0:0] ap_phi_mux_exitcond4_phi_fu_431_p4;
reg   [5:0] ap_phi_mux_pkern_phi_fu_442_p4;
reg   [1:0] ap_phi_mux_wkern_phi_fu_453_p4;
reg   [7:0] ap_phi_mux_indvar_flatten1_phi_fu_464_p4;
reg   [8:0] ap_phi_mux_indvar_flatten2_phi_fu_475_p4;
reg   [1:0] ap_phi_mux_hkern_phi_fu_486_p4;
wire   [63:0] tmp_29_cast_fu_860_p1;
wire   [15:0] out_val_V_fu_867_p5;
reg    ap_block_pp1_stage0_01001;
wire   [6:0] hout_1_fu_509_p2;
wire   [6:0] tmp_4_fu_523_p2;
wire   [6:0] tmp_7_fu_551_p2;
wire   [15:0] tmp_7_cast_fu_557_p1;
wire   [0:0] slt_fu_561_p2;
wire   [0:0] rev_fu_567_p2;
wire   [0:0] tmp_5_fu_573_p2;
wire   [0:0] tmp_6_fu_584_p2;
wire   [0:0] tmp_9_fu_590_p2;
wire   [0:0] tmp_8_fu_596_p2;
wire   [0:0] tmp_10_fu_602_p2;
wire   [0:0] tmp2_fu_614_p2;
wire   [0:0] tmp1_fu_608_p2;
wire   [10:0] tmp_14_fu_632_p3;
wire   [5:0] tmp_16_fu_644_p3;
wire   [12:0] p_shl3_cast_fu_652_p1;
wire   [12:0] p_shl2_cast_fu_640_p1;
wire   [12:0] tmp_17_fu_656_p2;
wire   [12:0] tmp_18_fu_662_p1;
wire   [12:0] tmp_19_fu_666_p2;
wire   [0:0] not_exitcond_flatten_fu_716_p2;
wire   [1:0] wkern_mid_fu_708_p3;
wire   [0:0] exitcond_mid_fu_722_p2;
wire   [0:0] tmp_21_fu_734_p2;
wire   [1:0] wkern_1_fu_728_p2;
wire   [6:0] tmp_27_cast_fu_756_p1;
wire   [7:0] indvar_flatten_op_fu_771_p2;
wire   [1:0] hkern_1_fu_809_p2;
wire   [11:0] tmp_22_fu_823_p3;
wire   [6:0] tmp_23_fu_834_p3;
wire   [12:0] p_shl5_cast_fu_841_p1;
wire   [12:0] p_shl4_cast_fu_830_p1;
wire   [12:0] tmp_24_fu_845_p2;
wire   [12:0] tmp_22_cast_fu_851_p1;
wire   [12:0] tmp_25_fu_854_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_condition_116;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

line_buffer_13_bubkb #(
    .DataWidth( 16 ),
    .AddressRange( 2112 ),
    .AddressWidth( 12 ))
buffer_val_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_val_0_V_address0),
    .ce0(buffer_val_0_V_ce0),
    .we0(buffer_val_0_V_we0),
    .d0(buffer_val_1_V_q0),
    .q0(buffer_val_0_V_q0)
);

line_buffer_13_bucud #(
    .DataWidth( 16 ),
    .AddressRange( 2112 ),
    .AddressWidth( 12 ))
buffer_val_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_val_1_V_address0),
    .ce0(buffer_val_1_V_ce0),
    .q0(buffer_val_1_V_q0),
    .address1(buffer_val_1_V_addr_reg_959),
    .ce1(buffer_val_1_V_ce1),
    .we1(buffer_val_1_V_we1),
    .d1(buffer_val_2_V_q0)
);

line_buffer_13_bucud #(
    .DataWidth( 16 ),
    .AddressRange( 2112 ),
    .AddressWidth( 12 ))
buffer_val_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffer_val_2_V_address0),
    .ce0(buffer_val_2_V_ce0),
    .q0(buffer_val_2_V_q0),
    .address1(buffer_val_2_V_addr_reg_965),
    .ce1(buffer_val_2_V_ce1),
    .we1(buffer_val_2_V_we1),
    .d1(ap_phi_reg_pp0_iter1_tmp_13_reg_354)
);

line_buffer_13_mueOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
line_buffer_13_mueOg_U1(
    .din0(buffer_val_0_V_q0),
    .din1(buffer_val_1_V_q0),
    .din2(buffer_val_2_V_q0),
    .din3(hkern_mid2_reg_1038),
    .dout(out_val_V_fu_867_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond3_fu_678_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_578_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_578_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_flatten2_fu_803_p2 == 1'd1))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_116)) begin
        if ((out_of_bounds_reg_940 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_tmp_13_reg_354 <= 16'd0;
        end else if ((out_of_bounds_reg_940 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_tmp_13_reg_354 <= input_V_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_tmp_13_reg_354 <= ap_phi_reg_pp0_iter0_tmp_13_reg_354;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_499_p2 == 1'd1))) begin
        exitcond1_reg_252 <= 1'd0;
    end else if (((exitcond_flatten1_fu_890_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        exitcond1_reg_252 <= exitcond2_fu_884_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond4_reg_427 <= exitcond_reg_1024;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
        exitcond4_reg_427 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond_flatten3_reg_415 <= exitcond_flatten_reg_1029;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
        exitcond_flatten3_reg_415 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        hin_2_reg_322 <= hin_s_reg_275;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        hin_2_reg_322 <= hin_3_reg_390;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (or_cond_reg_936 == 1'd1))) begin
        if (((tmp_15_fu_697_p2 == 1'd0) & (tmp_12_fu_684_p2 == 1'd0))) begin
            hin_3_reg_390 <= hin_fu_690_p2;
        end else if ((tmp_12_fu_684_p2 == 1'd1)) begin
            hin_3_reg_390 <= hin_2_reg_322;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_578_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        hin_4_reg_366 <= hin_2_reg_322;
    end else if (((tmp_12_fu_684_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (tmp_15_fu_697_p2 == 1'd1) & (or_cond_reg_936 == 1'd1))) begin
        hin_4_reg_366 <= hin_fu_690_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_499_p2 == 1'd1))) begin
        hin_s_reg_275 <= 16'd0;
    end else if (((exitcond_flatten1_fu_890_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        hin_s_reg_275 <= hin_4_reg_366;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp1_iter1_exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        hkern_reg_482 <= hkern_mid2_reg_1038;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
        hkern_reg_482 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_499_p2 == 1'd1))) begin
        hout_reg_299 <= 7'd0;
    end else if (((exitcond_flatten1_fu_890_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        hout_reg_299 <= hout_mid2_reg_909;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        indvar_flatten1_reg_460 <= indvar_flatten_next_reg_1014;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
        indvar_flatten1_reg_460 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        indvar_flatten2_reg_471 <= indvar_flatten_next2_reg_1019;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
        indvar_flatten2_reg_471 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_499_p2 == 1'd1))) begin
        indvar_flatten_reg_310 <= 12'd0;
    end else if (((exitcond_flatten1_fu_890_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        indvar_flatten_reg_310 <= indvar_flatten_next1_reg_920;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_reg_971 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pin_reg_343 <= pin_1_reg_944;
    end else if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_578_p2 == 1'd1))) begin
        pin_reg_343 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        pkern_reg_438 <= pkern_1_reg_1009;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
        pkern_reg_438 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_499_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_reg_241 <= tmp_1_fu_493_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_reg_241 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        win_2_reg_333 <= win_138_cast_fu_505_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        win_2_reg_333 <= win_3_reg_402;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (or_cond_reg_936 == 1'd1))) begin
        if (((tmp_15_fu_697_p2 == 1'd0) & (tmp_12_fu_684_p2 == 1'd0))) begin
            win_3_reg_402 <= 16'd0;
        end else if ((tmp_12_fu_684_p2 == 1'd1)) begin
            win_3_reg_402 <= win_fu_702_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_578_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        win_4_reg_378 <= tmp_2_fu_539_p1;
    end else if (((tmp_12_fu_684_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (tmp_15_fu_697_p2 == 1'd1) & (or_cond_reg_936 == 1'd1))) begin
        win_4_reg_378 <= 15'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_499_p2 == 1'd1))) begin
        win_s_reg_264 <= 15'd0;
    end else if (((exitcond_flatten1_fu_890_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        win_s_reg_264 <= win_4_reg_378;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        wkern_reg_449 <= wkern_mid2_reg_999;
    end else if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
        wkern_reg_449 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_499_p2 == 1'd1))) begin
        wout_reg_287 <= 7'd0;
    end else if (((exitcond_flatten1_fu_890_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        wout_reg_287 <= wout_1_fu_879_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_reg_pp1_iter1_exitcond_flatten2_reg_1034 <= exitcond_flatten2_reg_1034;
        col_assign_reg_1004 <= col_assign_fu_760_p2;
        exitcond_flatten2_reg_1034 <= exitcond_flatten2_fu_803_p2;
        pkern_mid2_reg_993 <= pkern_mid2_fu_740_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_1_V_addr_reg_959 <= tmp_24_cast_fu_672_p1;
        buffer_val_2_V_addr_reg_965 <= tmp_24_cast_fu_672_p1;
        exitcond3_reg_971 <= exitcond3_fu_678_p2;
        tmp_24_cast_reg_954[12 : 0] <= tmp_24_cast_fu_672_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond_flatten_reg_1029 <= exitcond_flatten_fu_797_p2;
        exitcond_reg_1024 <= exitcond_fu_791_p2;
        indvar_flatten_next2_reg_1019 <= indvar_flatten_next2_fu_785_p2;
        indvar_flatten_next_reg_1014 <= indvar_flatten_next_fu_777_p3;
        pkern_1_reg_1009 <= pkern_1_fu_765_p2;
        wkern_mid2_reg_999 <= wkern_mid2_fu_748_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        hkern_mid2_reg_1038 <= hkern_mid2_fu_815_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        hout_mid2_reg_909 <= hout_mid2_fu_515_p3;
        indvar_flatten_next1_reg_920 <= indvar_flatten_next1_fu_533_p2;
        tmp_4_cast_reg_914[6 : 0] <= tmp_4_cast_fu_529_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        or_cond_reg_936 <= or_cond_fu_578_p2;
        wout_mid_reg_930 <= wout_mid_fu_543_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_578_p2 == 1'd1))) begin
        out_of_bounds_reg_940 <= out_of_bounds_fu_620_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pin_1_reg_944 <= pin_1_fu_626_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_exitcond4_phi_fu_431_p4 = exitcond_reg_1024;
    end else begin
        ap_phi_mux_exitcond4_phi_fu_431_p4 = exitcond4_reg_427;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_exitcond_flatten3_phi_fu_419_p4 = exitcond_flatten_reg_1029;
    end else begin
        ap_phi_mux_exitcond_flatten3_phi_fu_419_p4 = exitcond_flatten3_reg_415;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_reg_pp1_iter1_exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        ap_phi_mux_hkern_phi_fu_486_p4 = hkern_mid2_reg_1038;
    end else begin
        ap_phi_mux_hkern_phi_fu_486_p4 = hkern_reg_482;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_indvar_flatten1_phi_fu_464_p4 = indvar_flatten_next_reg_1014;
    end else begin
        ap_phi_mux_indvar_flatten1_phi_fu_464_p4 = indvar_flatten1_reg_460;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_indvar_flatten2_phi_fu_475_p4 = indvar_flatten_next2_reg_1019;
    end else begin
        ap_phi_mux_indvar_flatten2_phi_fu_475_p4 = indvar_flatten2_reg_471;
    end
end

always @ (*) begin
    if (((exitcond3_reg_971 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_pin_phi_fu_347_p4 = pin_1_reg_944;
    end else begin
        ap_phi_mux_pin_phi_fu_347_p4 = pin_reg_343;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_pkern_phi_fu_442_p4 = pkern_1_reg_1009;
    end else begin
        ap_phi_mux_pkern_phi_fu_442_p4 = pkern_reg_438;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_flatten2_reg_1034 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_wkern_phi_fu_453_p4 = wkern_mid2_reg_999;
    end else begin
        ap_phi_mux_wkern_phi_fu_453_p4 = wkern_reg_449;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buffer_val_0_V_address0 = tmp_29_cast_fu_860_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        buffer_val_0_V_address0 = tmp_24_cast_reg_954;
    end else begin
        buffer_val_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        buffer_val_0_V_ce0 = 1'b1;
    end else begin
        buffer_val_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_0_V_we0 = 1'b1;
    end else begin
        buffer_val_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buffer_val_1_V_address0 = tmp_29_cast_fu_860_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_val_1_V_address0 = tmp_24_cast_fu_672_p1;
    end else begin
        buffer_val_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        buffer_val_1_V_ce0 = 1'b1;
    end else begin
        buffer_val_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_1_V_ce1 = 1'b1;
    end else begin
        buffer_val_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_1_V_we1 = 1'b1;
    end else begin
        buffer_val_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        buffer_val_2_V_address0 = tmp_29_cast_fu_860_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_val_2_V_address0 = tmp_24_cast_fu_672_p1;
    end else begin
        buffer_val_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        buffer_val_2_V_ce0 = 1'b1;
    end else begin
        buffer_val_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_2_V_ce1 = 1'b1;
    end else begin
        buffer_val_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        buffer_val_2_V_we1 = 1'b1;
    end else begin
        buffer_val_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((out_of_bounds_reg_940 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_V_blk_n = input_V_V_empty_n;
    end else begin
        input_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_of_bounds_reg_940 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_V_V_read = 1'b1;
    end else begin
        input_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        output_V_V_blk_n = output_V_V_full_n;
    end else begin
        output_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_V_V_write = 1'b1;
    end else begin
        output_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_3_fu_499_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (or_cond_fu_578_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & ((or_cond_reg_936 == 1'd0) | ((tmp_12_fu_684_p2 == 1'd0) & (tmp_15_fu_697_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (exitcond_flatten1_fu_890_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_of_bounds_reg_940 == 1'd0) & (input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_of_bounds_reg_940 == 1'd0) & (input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

assign ap_block_state10_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp1_stage0_iter2 = (output_V_V_full_n == 1'b0);
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter0 = ((out_of_bounds_reg_940 == 1'd0) & (input_V_V_empty_n == 1'b0));
end

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_116 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_tmp_13_reg_354 = 'bx;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign col_assign_fu_760_p2 = (wout_mid_reg_930 + tmp_27_cast_fu_756_p1);

assign exitcond2_fu_884_p2 = ((wout_1_fu_879_p2 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond3_fu_678_p2 = ((ap_phi_mux_pin_phi_fu_347_p4 == 5'd31) ? 1'b1 : 1'b0);

assign exitcond_flatten1_fu_890_p2 = ((indvar_flatten_reg_310 == 12'd4095) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_803_p2 = ((ap_phi_mux_indvar_flatten2_phi_fu_475_p4 == 9'd287) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_797_p2 = ((indvar_flatten_next_fu_777_p3 == 8'd96) ? 1'b1 : 1'b0);

assign exitcond_fu_791_p2 = ((pkern_1_fu_765_p2 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond_mid_fu_722_p2 = (not_exitcond_flatten_fu_716_p2 & ap_phi_mux_exitcond4_phi_fu_431_p4);

assign hin_fu_690_p2 = (hin_2_reg_322 + 16'd1);

assign hkern_1_fu_809_p2 = (ap_phi_mux_hkern_phi_fu_486_p4 + 2'd1);

assign hkern_mid2_fu_815_p3 = ((exitcond_flatten3_reg_415[0:0] === 1'b1) ? hkern_1_fu_809_p2 : ap_phi_mux_hkern_phi_fu_486_p4);

assign hout_1_fu_509_p2 = (hout_reg_299 + 7'd1);

assign hout_mid2_fu_515_p3 = ((exitcond1_reg_252[0:0] === 1'b1) ? hout_1_fu_509_p2 : hout_reg_299);

assign indvar_flatten_next1_fu_533_p2 = (indvar_flatten_reg_310 + 12'd1);

assign indvar_flatten_next2_fu_785_p2 = (ap_phi_mux_indvar_flatten2_phi_fu_475_p4 + 9'd1);

assign indvar_flatten_next_fu_777_p3 = ((ap_phi_mux_exitcond_flatten3_phi_fu_419_p4[0:0] === 1'b1) ? 8'd1 : indvar_flatten_op_fu_771_p2);

assign indvar_flatten_op_fu_771_p2 = (ap_phi_mux_indvar_flatten1_phi_fu_464_p4 + 8'd1);

assign not_exitcond_flatten_fu_716_p2 = (ap_phi_mux_exitcond_flatten3_phi_fu_419_p4 ^ 1'd1);

assign or_cond_fu_578_p2 = (tmp_5_fu_573_p2 | rev_fu_567_p2);

assign out_of_bounds_fu_620_p2 = (tmp2_fu_614_p2 | tmp1_fu_608_p2);

assign output_V_V_din = out_val_V_fu_867_p5;

assign p_shl2_cast_fu_640_p1 = tmp_14_fu_632_p3;

assign p_shl3_cast_fu_652_p1 = tmp_16_fu_644_p3;

assign p_shl4_cast_fu_830_p1 = tmp_22_fu_823_p3;

assign p_shl5_cast_fu_841_p1 = tmp_23_fu_834_p3;

assign pin_1_fu_626_p2 = (ap_phi_mux_pin_phi_fu_347_p4 + 5'd1);

assign pkern_1_fu_765_p2 = (pkern_mid2_fu_740_p3 + 6'd1);

assign pkern_mid2_fu_740_p3 = ((tmp_21_fu_734_p2[0:0] === 1'b1) ? 6'd0 : ap_phi_mux_pkern_phi_fu_442_p4);

assign rev_fu_567_p2 = (slt_fu_561_p2 ^ 1'd1);

assign slt_fu_561_p2 = (($signed(tmp_7_cast_fu_557_p1) < $signed(win_2_reg_333)) ? 1'b1 : 1'b0);

assign tmp1_fu_608_p2 = (tmp_9_fu_590_p2 | tmp_6_fu_584_p2);

assign tmp2_fu_614_p2 = (tmp_8_fu_596_p2 | tmp_10_fu_602_p2);

assign tmp_10_fu_602_p2 = (($signed(win_2_reg_333) > $signed(16'd64)) ? 1'b1 : 1'b0);

assign tmp_12_fu_684_p2 = (($signed(win_2_reg_333) < $signed(16'd65)) ? 1'b1 : 1'b0);

assign tmp_14_fu_632_p3 = {{ap_phi_mux_pin_phi_fu_347_p4}, {6'd0}};

assign tmp_15_fu_697_p2 = (($signed(hin_fu_690_p2) > $signed(tmp_4_cast_reg_914)) ? 1'b1 : 1'b0);

assign tmp_16_fu_644_p3 = {{ap_phi_mux_pin_phi_fu_347_p4}, {1'd0}};

assign tmp_17_fu_656_p2 = (p_shl3_cast_fu_652_p1 + p_shl2_cast_fu_640_p1);

assign tmp_18_fu_662_p1 = win_2_reg_333[12:0];

assign tmp_19_fu_666_p2 = (tmp_17_fu_656_p2 + tmp_18_fu_662_p1);

assign tmp_1_fu_493_p2 = (tmp_reg_241 + 5'd1);

assign tmp_21_fu_734_p2 = (exitcond_mid_fu_722_p2 | ap_phi_mux_exitcond_flatten3_phi_fu_419_p4);

assign tmp_22_cast_fu_851_p1 = col_assign_reg_1004;

assign tmp_22_fu_823_p3 = {{pkern_mid2_reg_993}, {6'd0}};

assign tmp_23_fu_834_p3 = {{pkern_mid2_reg_993}, {1'd0}};

assign tmp_24_cast_fu_672_p1 = tmp_19_fu_666_p2;

assign tmp_24_fu_845_p2 = (p_shl5_cast_fu_841_p1 + p_shl4_cast_fu_830_p1);

assign tmp_25_fu_854_p2 = (tmp_24_fu_845_p2 + tmp_22_cast_fu_851_p1);

assign tmp_27_cast_fu_756_p1 = wkern_mid2_fu_748_p3;

assign tmp_29_cast_fu_860_p1 = tmp_25_fu_854_p2;

assign tmp_2_fu_539_p1 = win_2_reg_333[14:0];

assign tmp_3_fu_499_p2 = ((tmp_reg_241 == 5'd31) ? 1'b1 : 1'b0);

assign tmp_4_cast_fu_529_p1 = tmp_4_fu_523_p2;

assign tmp_4_fu_523_p2 = (hout_mid2_fu_515_p3 + 7'd2);

assign tmp_5_fu_573_p2 = (($signed(hin_2_reg_322) < $signed(tmp_4_cast_reg_914)) ? 1'b1 : 1'b0);

assign tmp_6_fu_584_p2 = (($signed(hin_2_reg_322) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign tmp_7_cast_fu_557_p1 = tmp_7_fu_551_p2;

assign tmp_7_fu_551_p2 = (7'd2 + wout_mid_fu_543_p3);

assign tmp_8_fu_596_p2 = (($signed(win_2_reg_333) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign tmp_9_fu_590_p2 = (($signed(hin_2_reg_322) > $signed(16'd64)) ? 1'b1 : 1'b0);

assign win_138_cast_fu_505_p1 = win_s_reg_264;

assign win_fu_702_p2 = (win_2_reg_333 + 16'd1);

assign wkern_1_fu_728_p2 = (wkern_mid_fu_708_p3 + 2'd1);

assign wkern_mid2_fu_748_p3 = ((exitcond_mid_fu_722_p2[0:0] === 1'b1) ? wkern_1_fu_728_p2 : wkern_mid_fu_708_p3);

assign wkern_mid_fu_708_p3 = ((ap_phi_mux_exitcond_flatten3_phi_fu_419_p4[0:0] === 1'b1) ? 2'd0 : ap_phi_mux_wkern_phi_fu_453_p4);

assign wout_1_fu_879_p2 = (wout_mid_reg_930 + 7'd1);

assign wout_mid_fu_543_p3 = ((exitcond1_reg_252[0:0] === 1'b1) ? 7'd0 : wout_reg_287);

always @ (posedge ap_clk) begin
    tmp_4_cast_reg_914[15:7] <= 9'b000000000;
    tmp_24_cast_reg_954[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //line_buffer_13
