-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.4d)
-- from file main.cph, on 2019-05-08 at 15:51:51, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;

package edgeDetectionTutorial_globals is
  type array1024_u9 is array (0 to 1023) of unsigned(8 downto 0);
  type array1024_b is array (0 to 1023) of boolean;
function lsh(x:unsigned(8 downto 0)) return unsigned;
end edgeDetectionTutorial_globals;

package body edgeDetectionTutorial_globals is
function lsh(x:unsigned(8 downto 0)) return unsigned is
  begin
    return SHIFT_LEFT(x, 1);
  end lsh;
end edgeDetectionTutorial_globals;
